
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 29 17:55:10 CEST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SIGNED = 42;
  public static final int ANDEQ = 29;
  public static final int GT = 83;
  public static final int CONST = 46;
  public static final int NOTEQ = 19;
  public static final int PLUSEQ = 25;
  public static final int REGISTER = 37;
  public static final int ENUM = 50;
  public static final int RBRACK = 72;
  public static final int SIZEOF = 10;
  public static final int COMMA = 67;
  public static final int RBRACE = 66;
  public static final int SHORT_TYPE = 39;
  public static final int RPAREN = 70;
  public static final int FLOAT_TYPE = 44;
  public static final int LBRACK = 71;
  public static final int LT = 82;
  public static final int ANDAND = 20;
  public static final int OROR = 21;
  public static final int STRUCT = 49;
  public static final int LBRACE = 65;
  public static final int LPAREN = 69;
  public static final int XOREQ = 30;
  public static final int NOT = 75;
  public static final int CHAR_TYPE = 38;
  public static final int ERROR = 6;
  public static final int GOTO = 60;
  public static final int COMP = 76;
  public static final int EQ = 3;
  public static final int MOD = 81;
  public static final int INT_TYPE = 40;
  public static final int ADRESS = 74;
  public static final int PLUS = 78;
  public static final int QUESTION = 86;
  public static final int WHILE = 57;
  public static final int PTR_OP = 11;
  public static final int SWITCH = 56;
  public static final int DO = 58;
  public static final int FOR = 59;
  public static final int RSHIFTEQ = 28;
  public static final int DIV = 80;
  public static final int VOID = 48;
  public static final int EXTERN = 34;
  public static final int MULT = 79;
  public static final int RETURN = 63;
  public static final int ELSE = 55;
  public static final int BREAK = 62;
  public static final int GTEQ = 17;
  public static final int DOT = 2;
  public static final int DOUBLE_TYPE = 45;
  public static final int NULL_LITERAL = 5;
  public static final int EQEQ = 18;
  public static final int EOF = 0;
  public static final int SEMICOLON = 64;
  public static final int TYPE_NAME = 32;
  public static final int DEFAULT = 53;
  public static final int MULTEQ = 22;
  public static final int MINUS = 77;
  public static final int CONSTANT = 8;
  public static final int LTEQ = 16;
  public static final int OR = 85;
  public static final int error = 1;
  public static final int DIVEQ = 23;
  public static final int LSHIFTEQ = 27;
  public static final int CONTINUE = 61;
  public static final int IF = 54;
  public static final int POINT_TYPE = 73;
  public static final int UNSIGNED = 43;
  public static final int ID = 7;
  public static final int MODEQ = 24;
  public static final int LONG_TYPE = 41;
  public static final int MINUSMINUS = 13;
  public static final int COLON = 68;
  public static final int VOLATILE = 47;
  public static final int OREQ = 31;
  public static final int CASE = 52;
  public static final int PLUSPLUS = 12;
  public static final int RSHIFT = 15;
  public static final int STRING = 9;
  public static final int AND = 4;
  public static final int ELLIPSIS = 51;
  public static final int STATIC = 35;
  public static final int LSHIFT = 14;
  public static final int TYPEDEF = 33;
  public static final int XOR = 84;
  public static final int AUTO = 36;
  public static final int MINUSEQ = 26;
}

