
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 14 10:19:37 CEST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SIGNED = 46;
  public static final int OCT_CONSTANT = 11;
  public static final int ANDEQ = 33;
  public static final int GT = 87;
  public static final int CONST = 50;
  public static final int NOTEQ = 23;
  public static final int PLUSEQ = 29;
  public static final int REGISTER = 41;
  public static final int ENUM = 54;
  public static final int RBRACK = 76;
  public static final int SIZEOF = 14;
  public static final int COMMA = 71;
  public static final int RBRACE = 70;
  public static final int SHORT_TYPE = 43;
  public static final int RPAREN = 74;
  public static final int FLOAT_TYPE = 48;
  public static final int LBRACK = 75;
  public static final int LT = 86;
  public static final int ANDAND = 24;
  public static final int OROR = 25;
  public static final int CHAR_CONSTANT = 8;
  public static final int STRUCT = 53;
  public static final int LBRACE = 69;
  public static final int LPAREN = 73;
  public static final int XOREQ = 34;
  public static final int NOT = 79;
  public static final int CHAR_TYPE = 42;
  public static final int ERROR = 6;
  public static final int HEX_CONSTANT = 12;
  public static final int GOTO = 64;
  public static final int COMP = 80;
  public static final int EQ = 3;
  public static final int MOD = 85;
  public static final int INT_TYPE = 44;
  public static final int ADRESS = 78;
  public static final int PLUS = 82;
  public static final int QUESTION = 90;
  public static final int WHILE = 61;
  public static final int PTR_OP = 15;
  public static final int SWITCH = 60;
  public static final int DO = 62;
  public static final int FOR = 63;
  public static final int RSHIFTEQ = 32;
  public static final int DIV = 84;
  public static final int VOID = 52;
  public static final int EXTERN = 38;
  public static final int MULT = 83;
  public static final int RETURN = 67;
  public static final int ELSE = 59;
  public static final int REAL_CONSTANT = 10;
  public static final int BREAK = 66;
  public static final int GTEQ = 21;
  public static final int DOT = 2;
  public static final int DOUBLE_TYPE = 49;
  public static final int NULL_LITERAL = 5;
  public static final int EQEQ = 22;
  public static final int EOF = 0;
  public static final int SEMICOLON = 68;
  public static final int TYPE_NAME = 36;
  public static final int DEFAULT = 57;
  public static final int MULTEQ = 26;
  public static final int MINUS = 81;
  public static final int LTEQ = 20;
  public static final int OR = 89;
  public static final int error = 1;
  public static final int DIVEQ = 27;
  public static final int LSHIFTEQ = 31;
  public static final int CONTINUE = 65;
  public static final int IF = 58;
  public static final int POINT_TYPE = 77;
  public static final int UNSIGNED = 47;
  public static final int ID = 7;
  public static final int MODEQ = 28;
  public static final int LONG_TYPE = 45;
  public static final int MINUSMINUS = 17;
  public static final int COLON = 72;
  public static final int VOLATILE = 51;
  public static final int OREQ = 35;
  public static final int CASE = 56;
  public static final int PLUSPLUS = 16;
  public static final int RSHIFT = 19;
  public static final int STRING = 13;
  public static final int AND = 4;
  public static final int ELLIPSIS = 55;
  public static final int STATIC = 39;
  public static final int LSHIFT = 18;
  public static final int INT_CONSTANT = 9;
  public static final int TYPEDEF = 37;
  public static final int XOR = 88;
  public static final int AUTO = 40;
  public static final int MINUSEQ = 30;
}

