
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Apr 10 11:18:01 PDT 2005
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
 public static final int EOF = 0;
  public static final int BREAK = 1;
  public static final int BYTE = 2;
  public static final int CASE = 3;
 public static final int CATCH = 4;  
  public static final int CHAR_TYPE=5;
  public static final int CONST=6;
  public static final int CONTINUE=7;
  public static final int DO=8;
  public static final int DOUBLE_TYPE=9;
  public static final int ELSE=10;
  public static final int EXTERN=11;
  public static final int FINAL=12;
  public static final int FINALLY=13;
  public static final int FLOAT_TYPE=14;
  public static final int FOR=15;
  public static final int DEFAULT=16;
  public static final int INT_TYPE=17;
  public static final int LONG_TYPE=18;
  public static final int GOTO=19;
  public static final int IF=20; 
  public static final int SHORT_TYPE=21;
  public static final int SWITCH=22;
  public static final int RETURN=23;
  public static final int VOID=24;
  public static final int STATIC=25;
  public static final int WHILE=26;
  public static final int TYPEDEF=27;
  public static final int VOLATILE=28;
  public static final int NULL_LITERAL=29;
 public static final int LPAREN=30;
 public static final int RPAREN=31;
 public static final int LBRACE=32;
 public static final int RBRACE=33;
  public static final int LBRACK=34;
  public static final int RBRACK=35;
  public static final int SEMICOLON=36;
  public static final int COMMA=37;
 public static final int DOT=38;
  
 
 public static final int EQ=39;
 public static final int GT=40;
 public static final int LT=41;
 public static final int NOT=42;
 public static final int COMP=43;
 public static final int QUESTION=44;
  public static final int COLON=45;
  public static final int EQEQ=46;
 public static final int LTEQ=47;
 public static final int GTEQ=48;
public static final int NOTEQ=49;
  public static final int ANDAND=50;
  public static final int OROR=51;
  public static final int PLUSPLUS=52;
public static final int MINUSMINUS=53;
 public static final int PLUS=54;
 public static final int MINUS=55;
 public static final int MULT=56;
 public static final int DIV=57;
  public static final int AND=58;
  public static final int OR=59;
  public static final int XOR=60;
 public static final int MOD=61;
public static final int LSHIFT=62;
 public static final int RSHIFT=63;
 public static final int URSHIFT=64;
public static final int PLUSEQ=65;
  public static final int MINUSEQ=66;
  public static final int MULTEQ=67;
 public static final int DIVEQ=68;
 public static final int ANDEQ=69;
 public static final int OREQ=70;
 public static final int XOREQ=71;
 public static final int MODEQ=72;
  public static final int LSHIFTEQ=73;
 public static final int RSHIFTEQ=74;
  public static final int URSHIFTEQ=75;
 public static final int ID = 76;

public static final int CONSTANT = 80;
public static final int ERROR = 81;
public static final int STRING = 82;
public static final int MEM_ID = 84;
public static final int ENUM = 85;
public static final int REGISTER = 86;
public static final int SIZEOF = 87;
public static final int SIGNED = 88;
}

